# -*- coding: utf-8 -*-
"""Practices python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l7_jaGwUNZis1xkCwz0QTWcfKxWbxZeO

input("

PRACTICE #1, DAYS LIVED
"""

# Días de cada mes
enero = 31
febrero = 28
marzo = 31
abril = 30
mayo = 31
junio = 30
julio = 31
agosto = 31
septiembre = 30
octubre = 31
noviembre = 30
diciembre = 31

# Preguntar datos
nombre = input("¿Cómo te llamas? ")

print("Fecha de nacimiento:")
dia_nac = int(input("Día: "))
mes_nac = int(input("Mes (1-12): "))
año_nac = int(input("Año: "))

print("Fecha de hoy:")
dia_hoy = int(input("Día: "))
mes_hoy = int(input("Mes (1-12): "))
año_actual = int(input("Año: "))

# Meses en lista (para sumar días)
meses = [0, enero, febrero, marzo, abril, mayo, junio, julio, agosto, septiembre, octubre, noviembre, diciembre]

# Sumar días de los meses completos del año de nacimiento
dias_restantes_nac = 365
for m in range(1, mes_nac):
    dias_restantes_nac = dias_restantes_nac - meses[m]
dias_restantes_nac = dias_restantes_nac - dia_nac

# Sumar días de los meses completos de este año
dias_hasta_hoy = 0
for m in range(1, mes_hoy):
    dias_hasta_hoy = dias_hasta_hoy + meses[m]
dias_hasta_hoy = dias_hasta_hoy + dia_hoy

# Calcular total
años_completos = año_actual - año_nac - 1
dias_vividos = 365 * años_completos + dias_restantes_nac + dias_hasta_hoy

# Resultado
print("Hola", nombre, "has vivido", dias_vividos, "días")

"""PRACTICE #2 DAYS LIVED IN THE YEAR AND LEFT FOR CHRISTMAS"""

nombre=input("Como te llamas?")
dias=int(input("Dia de hoy?"))
meses=int(input("Mes de hoy?"))
años=int(input("Año de hoy"))

enero=31

dias_transcurridos=enero+dias
año=365-6
dias_navidad=año-dias_transcurridos

print(f"Hola {nombre} estás en el día {dias_transcurridos} del año y faltan {dias_navidad} días para que sea navidad")